version: '2.1'
services:
  stormtrooper:
    build: 
      context: ./StormTrooper
      dockerfile: Dockerfile
    container_name: stormtrooper
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: on-failure
    volumes:
    - ./StormTrooper/resources:/StormTrooper/resources
    - ./StormTrooper/logs:/StormTrooper/logs
    environment:
      - RABBITMQ_HOST=rabbitmq

  supplier:
    build: 
      context: ./Supplier
      dockerfile: Dockerfile
    container_name: supplier
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./Supplier/resources:/Supplier/resources
      - ./Supplier/logs:/Supplier/logs
    environment:
      - RABBITMQ_HOST=rabbitmq

  rabbitmq:
    logging: 
      driver: none
    container_name: rabbitmq
    image: rabbitmq:3-management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
        test: rabbitmq-diagnostics -q ping
        interval: 30s
        timeout: 30s
        retries: 3